In [1]:
import pandas
import matplotlib.pyplot as pyplot
import numpy
import sklearn
from xgboost import XGBClassifier

In [2]:
# Dataset obtained from kaggle: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud
data = pandas.read_csv('creditcard.csv')
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [3]:
# Most original columns were put through PCA (or something like that) for privacy.
# Time is the number of seconds from the first transaction in the data set. Amount is the transaction amount.
# And Class is 0 for no fraud has occured and 1 for fraud has occured.

# Also there are no null values, which is nice.
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [4]:
train_data, test_data = sklearn.model_selection.train_test_split(data, test_size=0.1, random_state=45)

In [5]:
train_data.describe()
# Roughly 0.17% of data entries have a class value of 1. So accuracy is a useless metric for
# evaluating whether a model can detect fraud.

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,256326.000000,256326.000000,256326.000000,256326.000000,256326.000000,256326.000000,256326.000000,256326.000000,256326.000000,256326.000000,...,256326.000000,256326.000000,256326.000000,256326.000000,256326.000000,256326.000000,256326.000000,256326.000000,256326.000000,256326.000000
mean,94859.328113,-0.001896,-0.000133,-0.000750,-0.000613,0.000124,0.000537,0.000804,-0.000778,-0.000632,...,-0.000376,-0.000561,-0.000321,0.000468,-0.000082,-0.000173,0.000235,-0.000201,88.523732,0.001697
std,47485.686190,1.961425,1.653179,1.517385,1.416430,1.385820,1.334190,1.245324,1.194151,1.099746,...,0.737298,0.726376,0.629004,0.605494,0.521129,0.481907,0.405459,0.327071,251.840728,0.041160
min,0.000000,-46.855047,-63.344698,-48.325589,-5.683171,-113.743307,-23.496714,-43.557242,-73.216718,-13.434066,...,-34.830382,-10.933144,-44.807735,-2.836627,-10.295397,-2.604551,-22.565679,-15.430084,0.000000,0.000000
25%,54238.250000,-0.922099,-0.598846,-0.890910,-0.849675,-0.692545,-0.767602,-0.553605,-0.209138,-0.643807,...,-0.228620,-0.542822,-0.162004,-0.354479,-0.317173,-0.326681,-0.070775,-0.052941,5.550000,0.000000
50%,84763.500000,0.014862,0.066432,0.179180,-0.021005,-0.054096,-0.274141,0.040825,0.021966,-0.052393,...,-0.029987,0.005671,-0.011186,0.041078,0.015465,-0.052117,0.001429,0.011277,22.000000,0.000000
75%,139366.750000,1.315448,0.805119,1.027462,0.741919,0.613082,0.398818,0.571258,0.327729,0.597383,...,0.186247,0.527980,0.147605,0.439461,0.350666,0.240387,0.091373,0.078518,77.000000,0.000000
max,172792.000000,2.454930,22.057729,9.382558,16.875344,34.099309,73.301626,120.589494,20.007208,15.594995,...,27.202839,10.503090,22.528412,4.584549,7.519589,3.517346,31.612198,22.620072,25691.160000,1.000000

In [6]:
# There are some non-zero correlations between class and the features. But there are many features
# that seem to be uncorrelated with class.
train_data.corr()['Class']

Time     -0.012671
V1       -0.103669
V2        0.092938
V3       -0.195929
V4        0.134371
V5       -0.098471
V6       -0.042563
V7       -0.191902
V8        0.016207
V9       -0.099157
V10      -0.219851
V11       0.154528
V12      -0.261165
V13      -0.004764
V14      -0.299623
V15      -0.004504
V16      -0.198673
V17      -0.328769
V18      -0.113660
V19       0.036571
V20       0.021039
V21       0.041570
V22       0.000414
V23      -0.001064
V24      -0.006826
V25       0.002185
V26       0.004111
V27       0.016518
V28       0.007756
Amount    0.006375
Class     1.000000
Name: Class, dtype: float64

In [7]:
# Some means of features seem to be quite different depending on which class they're filtered by.
train_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94884.136027,0.006488,-0.006468,0.011508,-0.008461,0.005750,0.002879,0.010657,-0.001576,0.003864,...,-0.000988,-0.001639,-0.000574,-0.000294,0.000638,-0.000129,-0.000255,-0.000041,-0.000306,88.457535
1,80265.944828,-4.933661,3.726318,-7.211451,4.615556,-3.309648,-1.376782,-5.795418,0.468619,-2.645469,...,0.395586,0.743001,0.006739,-0.016550,-0.099771,0.027532,0.047872,0.162671,0.061323,127.464506

In [8]:
# create our train and test splits
x_train, x_test = train_data.drop('Class', axis=1), test_data.drop('Class', axis=1)
y_train, y_test = train_data['Class'], test_data['Class']
y_train.shape, y_test.shape

((256326,), (28481,))

In [9]:
kfolds = sklearn.model_selection.KFold(n_splits=5, shuffle=True, random_state=15)

In [35]:
# We'll use XGBoost to build a tree ensemble. We'll use cross-validation to select its parameters.
boost_model = XGBClassifier()

# I started out with a wider grid search. I would then re-run the grid search over a 
# new range including the previous iteration's best parameters. And then I would repeat this process
# until it seemed to stop making a meaningful difference to the score.
max_depth = [6]
subsample = [0.7]
learning_rate = [0.1]
n_estimators = [400, 450]
param_map = {'max_depth':max_depth, 'subsample':subsample, 'learning_rate':learning_rate, 
            'n_estimators':n_estimators}

# Used average precision as our scoring metric.
metric = 'average_precision'
grid = sklearn.model_selection.GridSearchCV(boost_model, param_map, refit=True, cv=kfolds, scoring=metric)
grid.fit(x_train, y_train)
print(grid.best_score_)
grid.best_params_

0.8582659755548093

{'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 400, 'subsample': 0.7}

In [36]:
# Next we determine what probability threshold to use when predicting fraud has occured will
# maximise a cross-validated f1 score.

best_boost = grid.best_estimator_
boost_tuned = sklearn.model_selection.TunedThresholdClassifierCV(best_boost, scoring='f1', cv=kfolds)
boost_tuned.fit(x_train, y_train)
boost_tuned.best_threshold_, boost_tuned.best_score_

# We obtain a slightly larger cross validated f1-score from our boost model. And our probility threshold
# is set to roughly 10%.

(np.float32(0.09090871), np.float64(0.8639851862056528))

In [37]:
print(sklearn.metrics.classification_report(y_test, boost_tuned.predict(x_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     28424
           1       0.91      0.86      0.88        57

    accuracy                           1.00     28481
   macro avg       0.95      0.93      0.94     28481
weighted avg       1.00      1.00      1.00     28481

In [ ]:
# We obtain a test f1-score of 0.88 with a precision of 0.91 and a recall of 0.86.

# We could have also focused on either precision or recall when selecting our probability threshold
# if one of them should be considered a higher priority than the other.